language: python
python:
  - "3.9"

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  # Run unit tests
  - pytest -q

  # Build Docker image (no push yet)
  - IMAGE_NAME="mcp-todo"
  - docker build -t "$IMAGE_NAME:test" .
